[project]
name = "python-garminconnect"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "Ron Klinkien", email = "ron@cyberjunky.nl"},
    {name = "Shoaib Khan", email = "shoaib@evermeet.ca"},
]
dependencies = [
    "garth>=0.4.46",
    "withings-sync>=4.2.4",
]
readme = "README.md"
license = {text = "MIT"}
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: MacOS :: MacOS X",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: POSIX :: Linux",
]
keywords=["garmin connect", "api", "garmin"]
requires-python="==3.10.*"
[project.urls]
"Homepage" = "https://github.com/cyberjunky/python-garminconnect"
"Bug Tracker" = "https://github.com/cyberjunky/python-garminconnect/issues"

[tool.pytest.ini_options]
addopts = "--ignore=__pypackages__ --ignore-glob=*.yaml"

[tool.mypy]
ignore_missing_imports = true

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 79
known_first_party = "garminconnect"

[tool.pdm]
distribution = false
[tool.pdm.dev-dependencies]
dev = [
    "ipython",
    "ipdb",
    "ipykernel",
    "pandas",
    "matplotlib",
]
linting = [
    "black",
    "ruff",
    "mypy",
    "isort",
    "types-requests",
]
testing = [
    "coverage",
    "pytest",
    "pytest-vcr",
]
